# Generated by Django 3.2.6 on 2021-08-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyst', '0006_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='text',
            field=models.TextField(default=1, verbose_name='Текст'),
            preserve_default=False,
        ),
    ]
