# Generated by Django 3.2.6 on 2021-08-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyst', '0007_hashtag_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address_lng',
            field=models.TextField(blank=True, null=True, verbose_name='адрес(Кординаты)'),
        ),
    ]
