# Generated by Django 3.2.6 on 2021-08-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyst', '0008_alter_user_address_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.BooleanField(verbose_name='Пол'),
        ),
    ]
