version: '3.7'
services:
  react:
    build: ./react_frontend
    ports:
      - "3001:3000"
    volumes:
      - ./react_frontend:/app
  analytics:
    build: ./analytics_back
    volumes:
      - ./analytics_back:/app
